services:
  web:
    build: .
    restart: unless-stopped
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: cttest.tk.sg
    networks:
      devtksg:

networks:
  devtksg:
    external: true
